#!/bin/bash

# 🚀 GigaTalentos GitHub Actions Setup Script
# This script helps you set up the required GitHub secrets for deployment

echo "🚀 Setting up GitHub Actions for GigaTalentos deployment"
echo "============================================================"
echo ""

echo "📋 You need to add the following secrets to your GitHub repository:"
echo "Go to: Settings > Secrets and variables > Actions > New repository secret"
echo ""

echo "🔐 Required GitHub Secrets:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Get Vercel project info
echo "1. VERCEL_TOKEN"
echo "   📝 Get this from: https://vercel.com/account/tokens"
echo "   🎯 Create a new token with full access"
echo ""

echo "2. VERCEL_ORG_ID"
echo "   📝 Get this by running: vercel teams ls"
echo "   🎯 Use the ID of your team/personal account"
echo ""

echo "3. VERCEL_PROJECT_ID"
echo "   📝 Get this from your Vercel project settings"
echo "   🎯 Or run: vercel project ls"
echo ""

echo "4. Environment Variables (same as your .env.local):"
echo "   • MONGODB_URI"
echo "   • NEXTAUTH_SECRET"
echo "   • NEXTAUTH_URL (your production URL)"
echo "   • NEXT_PUBLIC_SUPABASE_URL"
echo "   • NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo ""

echo "🛠️ Setup Commands:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# 1. Login to Vercel CLI (if not already logged in)"
echo "vercel login"
echo ""
echo "# 2. Link your project (if not already linked)"
echo "vercel link"
echo ""
echo "# 3. Get your Vercel Organization ID"
echo "vercel teams ls"
echo ""
echo "# 4. Get your Vercel Project ID"
echo "vercel project ls"
echo ""
echo "# 5. Create a Vercel token"
echo "# Go to: https://vercel.com/account/tokens"
echo ""

echo "📄 Example GitHub Secrets Configuration:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Secret Name: VERCEL_TOKEN"
echo "Secret Value: vercel_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
echo ""
echo "Secret Name: VERCEL_ORG_ID"
echo "Secret Value: team_xxxxxxxxxxxxxxxxxxxxxx"
echo ""
echo "Secret Name: VERCEL_PROJECT_ID"
echo "Secret Value: prj_xxxxxxxxxxxxxxxxxxxxxx"
echo ""
echo "Secret Name: MONGODB_URI"
echo "Secret Value: mongodb+srv://info:eNXuLyRu6WwS9JKX@cluster0.fpl08cr.mongodb.net/..."
echo ""
echo "Secret Name: NEXTAUTH_SECRET"
echo "Secret Value: 8Vt9Ttn4fqYpEAtAuVRQPZ8RJy8lrZTzoZHGDqfCGBI="
echo ""
echo "Secret Name: NEXTAUTH_URL"
echo "Secret Value: https://your-production-domain.vercel.app"
echo ""
echo "Secret Name: NEXT_PUBLIC_SUPABASE_URL"
echo "Secret Value: https://comqeoxjtpxautycwvuk.supabase.co"
echo ""
echo "Secret Name: NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo "Secret Value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
echo ""

echo "🎯 GitHub Repository Settings URL:"
echo "https://github.com/carlosdenner/GigaTalentos/settings/secrets/actions"
echo ""

echo "✅ Once all secrets are configured, the workflow will:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. 🔍 Run quality checks (linting, type checking)"
echo "2. 🏗️ Build and test the application"
echo "3. 🚀 Deploy to Vercel preview (for PRs)"
echo "4. 🚀 Deploy to Vercel production (for main branch)"
echo "5. 🏥 Run health checks on production"
echo "6. 📊 Provide deployment summary"
echo ""

echo "🚨 Important Notes:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "• Make sure your repository is connected to Vercel"
echo "• Ensure all environment variables are correctly set"
echo "• The workflow will run on pushes to main/master branch"
echo "• PRs will get preview deployments with automatic comments"
echo "• Production deployments require manual approval if you set up environments"
echo ""

echo "🔧 Troubleshooting:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "• Check GitHub Actions logs if deployment fails"
echo "• Verify all secrets are correctly named and valued"
echo "• Ensure your Vercel project is properly configured"
echo "• Check that your MongoDB Atlas allows connections from Vercel IPs"
echo ""

echo "🎉 Happy Deploying!"
echo "Once configured, every push to main will automatically deploy to production!"
